import type { OverpassElement } from "./fetcher"

/**
 * Represents a normalized place record ready for Supabase insertion.
 * This omits the `id`, `created_at`, and `updated_at` fields which
 * are auto-generated by the database.
 */
export interface PlaceInsert {
  name: string
  slug: string
  type: "gym" | "boulder" | "crag" | "wall" | "other"
  environment: "indoor" | "outdoor"
  latitude: number
  longitude: number
  address: string | null
  city: string | null
  region: string | null
  country: string
  disciplines: string[]
  amenities: string[]
  description: string | null
  osm_id: number
  source: "osm"
  verified: boolean
}

/**
 * Infer place type from OSM tags.
 */
function inferType(tags: Record<string, string>): PlaceInsert["type"] {
  if (tags["leisure"] === "sports_centre" || tags["leisure"] === "fitness_centre") {
    return "gym"
  }
  if (tags["natural"] === "cliff") {
    return "crag"
  }
  if (tags["climbing:boulder"] === "yes") {
    return "boulder"
  }
  if (tags["climbing:sport"] === "yes" || tags["climbing:trad"] === "yes") {
    return "crag"
  }
  // If it has a name and sport=climbing but no other clues, default to "other"
  return "other"
}

/**
 * Infer environment (indoor vs outdoor) from OSM tags.
 */
function inferEnvironment(tags: Record<string, string>): PlaceInsert["environment"] {
  if (
    tags["leisure"] === "sports_centre" ||
    tags["leisure"] === "fitness_centre" ||
    tags["building"] ||
    tags["indoor"] === "yes"
  ) {
    return "indoor"
  }
  return "outdoor"
}

/**
 * Extract climbing disciplines from OSM tags.
 */
function extractDisciplines(tags: Record<string, string>): string[] {
  const disciplines: string[] = []
  if (tags["climbing:sport"] === "yes") disciplines.push("sport")
  if (tags["climbing:trad"] === "yes") disciplines.push("trad")
  if (tags["climbing:boulder"] === "yes") disciplines.push("bouldering")
  if (tags["climbing:toprope"] === "yes") disciplines.push("top-rope")
  if (tags["climbing:lead"] === "yes") disciplines.push("lead")
  if (tags["climbing:ice"] === "yes") disciplines.push("ice")
  return disciplines
}

/**
 * Generate a URL-safe slug from a name.
 */
function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
}

/**
 * Normalize a raw OSM element into a PlaceInsert record.
 * Returns null if the element is missing required data (name, coordinates).
 */
export function normalizeElement(element: OverpassElement): PlaceInsert | null {
  const tags = element.tags || {}
  const name = tags["name"]

  // Skip elements without a name — they're usually incomplete
  if (!name) return null

  // Get coordinates: nodes have lat/lon directly, ways have center
  const lat = element.lat ?? element.center?.lat
  const lon = element.lon ?? element.center?.lon

  if (lat === undefined || lon === undefined) return null

  const type = inferType(tags)
  const environment = inferEnvironment(tags)
  const disciplines = extractDisciplines(tags)

  return {
    name,
    slug: `${slugify(name)}-${element.id}`,
    type,
    environment,
    latitude: lat,
    longitude: lon,
    address: tags["addr:street"]
      ? `${tags["addr:housenumber"] || ""} ${tags["addr:street"]}`.trim()
      : null,
    city: tags["addr:city"] || null,
    region: tags["addr:province"] || tags["addr:state"] || null,
    country: tags["addr:country"] || "CA",
    disciplines,
    amenities: [],
    description: tags["description"] || null,
    osm_id: element.id,
    source: "osm",
    verified: false,
  }
}

/**
 * Normalize an array of Overpass elements, filtering out incomplete records.
 */
export function normalizeElements(elements: OverpassElement[]): PlaceInsert[] {
  const results: PlaceInsert[] = []

  for (const element of elements) {
    const place = normalizeElement(element)
    if (place) {
      results.push(place)
    }
  }

  // Deduplicate by slug (keep the first occurrence)
  const seen = new Set<string>()
  return results.filter((place) => {
    if (seen.has(place.slug)) return false
    seen.add(place.slug)
    return true
  })
}
